from common.utils.constants import Stat, RowType

NAME_FONT = ("AnotherDanger", "PHJVTN")

STAT_NAMES = " ".join([s.value for s in Stat])

font_type_mapping = {
    ("AnotherDanger", "PHJVTN"): [RowType.name],
    ("ACaslonPro-Italic", "BJKODK"): [RowType.creature_type, RowType.spellcasting],
    ("ACaslonPro-Bold", "BQNTVJ"): [RowType.ac],
    ("ACaslonPro-Bold-SC700", "XEVNPQ"): [RowType.stat_list],
    ("AnotherDanger-SC700", "GGHDYV"): [RowType.action_start],
    ("ACaslonPro-Regular", "PFPIWB"): [RowType.other],
    ("ACaslonPro-BoldItalic", "LODTLM"): [RowType.leg_action_start],
}


translations = {
    "a c t Ions": "Actions",
    "l e g e n d a ry a c t Ions": "Legendary Actions",
    "r e a c t Ions": "Reactions",
    "fi end": "Fiend",
    "s Tr": "Str",
    "D ex": "Dex",
    "C on": "Con",
    "i nT": "Int",
    "w is": "Wis",
    "C ha": "Cha",
    "Th rows": "throws",
    "fi re": "fire",
    "e ff ect": "effect",
    "Th e": "the",
    "petri fi ed": "petrified",
    "fi nger": "finger",
    "fl y": "fly",
    " - ": "-",
    "fl owing": "flowing",
    "Pl e asure": "Pleasure",
    "Duk e": "Duke",
    "E ff ect": "Effect",
    "fi lth": "filth",
    "Vual l": "Vuall",
    "T he": "the",
    "A bigor": "Abigor",
    "Al astor": "Alastor",
    "Ant aia": "Antaia",
    " t he ": " the ",
    "Que e n": "Queen",
    "Asak ku": "Asakku",
    "Ashme de": "Ashmede",
    "Azal ar": "Azalar",
    "Bal an": "Balan",
    "Mast e r": "Master",
    "Inf e rnal": "Infernal",
    "Be l drak e": "Beldrake",
    "Hunt e r": "Hunter",
    "Borge g": "Borgeg",
    "Cre sil": "Cresil",
    "Dar ba": "Darba",
    "Dist e nde r": "Distender",
    "E nforce r": "Enforcer",
    "E nt ropus": "Entropus",
    "E nve lope r": "Envelope",
    " nt": "nt",
    "E urynomus": "Eurynomus",
    "E at e r": "Eater",
    "F e lugon": "Felugon",
    "Face l e ss": "Faceless",
    "Fal st af f": "Falstaff",
    "Fl e sh": "Flesh",
    "Scul ptor": "Sculptor",
    " t e are r": "tearer",
    "Gl adiat rix": "Gladiatrix",
    "Hadrie l": "Hadriel",
    "Duche ss": "Duchess",
    "Dominat ion": "Domination",
    "Harl e quin": "Harlequin",
    "He l lwar de n": "Hellwarden",
    "He rl e kin": "Herlekin",
    "Hor de": "Horde",
    "De mon": "Demon",
    "St al k e r": "Stalker",
    "J ahi": "Jahi",
    "J il aiya": "Jilaiya",
    "K e re": "Kere",
    "K nock e r": "Knocker",
    "L e ast": "Least",
    "L e l": "Lel",
    "Nig h t": "Night",
    "L e sse r": "Lesser",
    "Ma baxa": "Mabaxa",
    "Mal grin": "Malgrin",
    "Unlif e": "Unlife",
    "st r Angl e r": "Strangler",
    "Mazare e n": "Mazareen",
    "Me rihim": "Merihim",
    "Ne rgal": "Nergal",
    "f et id": "fetid",
    "Orusul a": "Orusula",
    "Paigoe l": "Paigoel",
    "Mist re ss": "Mistress",
    "Pe rtobl e n": "Pertoblen",
    "Philot anus": "Philotanus",
    "Se duce r": "Seducer",
    "Torme ntor": "Tormentor",
    "Rashe de": "Rashede",
    "Sat hre e n": "Sathreen",
    "Se lidim": "Selidim",
    "Shisse n": "Shissen",
    "Slot he n": "Slothen",
    "Sol e sik": "Solesik",
    "Soul k e e pe r": "Soulkeeper",
    "Soul snif f e r": "Soulsniffer",
    "Spinde r": "Spinder",
    "Spit e": "Spite",
    "St riga": "Striga",
    "T aurge n": "Taurgen",
    "Tort he n": "Torthen",
    "Unde lon": "Undelon",
    "Vie rha ande r": "Vierhaander",
    "Xaie x": "Xaiex",
    "Zal l ax": "Zallax",
}

NON_NUM = non_num = "[^0-9]"
OPEN_PARAN = "("
